allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@4.20260529.0
  - wrangler@4.96.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - workerd
  - sharp
  - esbuild
